# Numpy数据裁剪

In [3]:
import numpy as np

# 生成随机小数uniform()函数
arr1 = np.random.uniform(1,24,6)
print(arr1)
result = np.round(arr1,2)  #对数组进行设置小数位数
result

[17.00301984  9.31726837 23.48446829  1.77760919 23.29201749 22.47549087]


array([17.  ,  9.32, 23.48,  1.78, 23.29, 22.48])

In [14]:
# numpy数据裁剪
import numpy as np

# hstack()  对两个一维数组进行头对尾的拼接
res1 = np.random.uniform(1,24,6)
re1 = np.round(res1,2)  #保留两位小数
res2 = np.random.uniform(1,23,6)
re2 = np.round(res2,2) 
print(re1)
print(re2)

result = np.hstack((re1,re2))
result




[21.54  3.17 21.42  2.72  4.03  3.03]
[10.35 13.42  1.4   9.07  9.95 20.72]


array([21.54,  3.17, 21.42,  2.72,  4.03,  3.03, 10.35, 13.42,  1.4 ,
        9.07,  9.95, 20.72])

## 一维数组和二维数组的无法拼接

In [34]:
# 两个二维数组的数据框拼接
# 进行每一行的数据拼接
# 行数必须相同

arr1 = np.round(np.random.uniform(3,23,(3,4)),1)
print(arr1)
print("-"*50)
arr5 = np.round(np.random.uniform(6,29,(3,4)),1)
print(arr5)

result = np.hstack((arr1,arr5))
result

[[10.5 21.9 12.3  4.4]
 [12.6 12.8 12.4 17.3]
 [21.8 22.   8.6  3.5]]
--------------------------------------------------
[[ 6.  11.1 18.4 17.6]
 [17.4 16.4  6.9 11.2]
 [17.8 27.2 22.5 15.9]]


array([[10.5, 21.9, 12.3,  4.4,  6. , 11.1, 18.4, 17.6],
       [12.6, 12.8, 12.4, 17.3, 17.4, 16.4,  6.9, 11.2],
       [21.8, 22. ,  8.6,  3.5, 17.8, 27.2, 22.5, 15.9]])

# vstack 纵向拼接

In [37]:
# 两个一维数组的拼接，数组的长度必须相同
# 也可以实现多处拼接

res1 = np.random.uniform(1,24,6)
re1 = np.round(res1,2)  #保留两位小数
res2 = np.random.uniform(1,23,6)
re2 = np.round(res2,2) 
print(re1)
print(re2)

np.vstack((re1,re2))

[23.66 10.35 13.39  3.92  5.31  3.09]
[14.4  10.2  14.92 11.9   9.92  7.86]


array([[23.66, 10.35, 13.39,  3.92,  5.31,  3.09],
       [14.4 , 10.2 , 14.92, 11.9 ,  9.92,  7.86]])

In [46]:
# 一组数组与二维数组进行vstack（）拼接
# 一维与Erwin拼接必须长度相同

import numpy as np

ar1 = np.random.randint(2,36,6)
print(ar1)
ar2 = np.round(np.random.uniform(3,38,(2,6)),2)
print(ar2)

result = np.vstack((ar1,ar2))
result


[34 15  4 26 14  5]
[[35.11 25.75 23.58 10.49 33.93 16.84]
 [35.15 20.23  3.79 30.28 30.83 19.96]]


array([[34.  , 15.  ,  4.  , 26.  , 14.  ,  5.  ],
       [35.11, 25.75, 23.58, 10.49, 33.93, 16.84],
       [35.15, 20.23,  3.79, 30.28, 30.83, 19.96]])

In [50]:
# 两个二位数组的拼接
# 将两个二位数组拼接成一个整体数组

ar4 = np.round(np.random.uniform(3,38,(2,6)),2)
ar3 = np.round(np.random.uniform(3,38,(2,6)),2)
print(ar3)
print(ar4)
print("-"*30)

np.vstack((ar3,ar4))

[[16.25 26.01 13.79  9.07  4.02 36.5 ]
 [32.77 19.63 15.76 14.18  8.27 27.84]]
[[19.65 37.95 24.18  6.92 27.27 25.3 ]
 [18.93  8.06 12.25 30.18 14.58 35.74]]
------------------------------


array([[16.25, 26.01, 13.79,  9.07,  4.02, 36.5 ],
       [32.77, 19.63, 15.76, 14.18,  8.27, 27.84],
       [19.65, 37.95, 24.18,  6.92, 27.27, 25.3 ],
       [18.93,  8.06, 12.25, 30.18, 14.58, 35.74]])

# concatenate()

In [4]:
# 

arr1 = np.random.randint(2,45,5)
arr2 = np.random.randint(2,45,5)
print(arr1)
print(arr2)
print("-"*30)

res = np.concatenate((arr1,arr2),axis=0)
res


[ 9 30 14  8 20]
[44 21 25 18 35]
------------------------------


array([ 9, 30, 14,  8, 20, 44, 21, 25, 18, 35])

In [7]:
arr = np.random.randint(32,56,6)

arr1 = arr.reshape(6,1)  #将一维数组转为6行1列的二维数组
arr1

array([[43],
       [52],
       [32],
       [51],
       [37],
       [36]])

# column_stack() 和row_stack()

In [19]:
# 一维与一维的拼接

arr1 = [np.random.randint(3,36,6) for i in range(5)]

result = np.column_stack(arr1)
print(result)
arr1

[[24  7 35 22 24]
 [22  4 34 15 17]
 [20 12 28  3 25]
 [10 18 30  8 13]
 [30 19 24 29  9]
 [ 4 18 34 31 13]]


[array([24, 22, 20, 10, 30,  4]),
 array([ 7,  4, 12, 18, 19, 18]),
 array([35, 34, 28, 30, 24, 34]),
 array([22, 15,  3,  8, 29, 31]),
 array([24, 17, 25, 13,  9, 13])]

In [29]:
# 二维和一维的拼接 column_stack()  只能是行行拼接

arr1 = np.random.randint(12,69,(5,6))
arr2 = np.random.randint(1000,9000,5)
print(arr1)
print(arr2)

result = np.column_stack((arr1,arr2))
result

[[56 35 65 37 52 68]
 [68 65 61 52 61 53]
 [42 58 18 16 39 15]
 [55 67 19 22 62 46]
 [65 34 53 20 61 33]]
[5028 6316 2943 4327 3909]


array([[  56,   35,   65,   37,   52,   68, 5028],
       [  68,   65,   61,   52,   61,   53, 6316],
       [  42,   58,   18,   16,   39,   15, 2943],
       [  55,   67,   19,   22,   62,   46, 4327],
       [  65,   34,   53,   20,   61,   33, 3909]])

In [32]:
# 二维和一维的拼接 row_stack()  只能是列列拼接

arr1 = np.random.randint(12,69,(5,6))
arr2 = np.random.randint(1000,9000,6)
print(arr1)
print(arr2)

res = np.row_stack((arr1,arr2))
res

[[33 48 40 64 30 28]
 [33 27 57 27 13 58]
 [16 65 66 56 37 13]
 [53 44 68 42 43 33]
 [52 30 64 13 53 34]]
[5762 3192 4356 2100 1477 3253]


array([[  33,   48,   40,   64,   30,   28],
       [  33,   27,   57,   27,   13,   58],
       [  16,   65,   66,   56,   37,   13],
       [  53,   44,   68,   42,   43,   33],
       [  52,   30,   64,   13,   53,   34],
       [5762, 3192, 4356, 2100, 1477, 3253]])

# 数据框的分割 hsplit和vsplit

In [40]:
arr1 = np.random.randint(31,69,(4,8))

np.hsplit(arr1,2)  #将arr1数据框垂直分割成两份，只能均分，需要被整除




[array([[42, 66, 57, 33],
        [61, 60, 56, 34],
        [63, 63, 42, 51],
        [64, 46, 52, 39]]), array([[53, 44, 49, 34],
        [63, 48, 43, 54],
        [55, 66, 55, 66],
        [47, 61, 58, 54]])]

In [43]:
# 将arr1水平切割成两份
result = np.vsplit(arr1,2)
result


[array([[42, 66, 57, 33, 53, 44, 49, 34],
        [61, 60, 56, 34, 63, 48, 43, 54]]),
 array([[63, 63, 42, 51, 55, 66, 55, 66],
        [64, 46, 52, 39, 47, 61, 58, 54]])]

In [ ]:
# 数据框

In [52]:
# 
import pandas as pd
import numpy as np
arr1 = pd.DataFrame(np.random.randint(12,69,(4,6)))

arr1["key1"] = list("abcd")
arr1["key2"] = list("mnbv")
arr1


0   1   2   3   4   5 key1 key2
0  43  25  67  19  53  56    a    m
1  64  34  32  33  59  52    b    n
2  16  13  48  65  43  54    c    b
3  14  41  26  33  36  15    d    v

In [56]:
# 设置键列
arr1.set_index(["key1","key2"])



0   1   2   3   4   5
key1 key2                        
a    m     43  25  67  19  53  56
b    n     64  34  32  33  59  52
c    b     16  13  48  65  43  54
d    v     14  41  26  33  36  15

# panel

In [65]:
dict1 = {"A":np.random.randint(12,399,(3,6)),
         "B":np.random.randint(12,399,(4,8)),
         "C":np.random.randint(12,399,(7,6))}

new1 = pd.Panel(dict1)

TypeError: object() takes no parameters

# 数据加载，存储，清理，转换，合并与重塑

In [68]:
res = pd.read_csv("D:\日用文件\数据分析文档\little.csv")
res


A1    B1    C1    D1
0  12  34.0  33.0   ada
1  23  43.0   NaN  faes
2  44  55.0  55.0    da
3  12   NaN  33.0   dad

In [5]:
import pandas as pd

# read_table 可以读取text格式和csv格式的
pd.read_table("D:\日用文件\数据分析文档\little.csv",sep = ",")

A1    B1    C1    D1
0  12  34.0  33.0   ada
1  23  43.0   NaN  faes
2  44  55.0  55.0    da
3  12   NaN  33.0   dad

In [7]:
#修改索引值
# 使用names属性修改索引值

pd.read_csv("D:\日用文件\数据分析文档\little.csv",names=list("abcd"))


a    b    c     d
0  A1   B1   C1    D1
1  12   34   33   ada
2  23   43  NaN  faes
3  44   55   55    da
4  12  NaN   33   dad

In [13]:
#以某一列作为索引行 
# 以b列替换默认的索引行

res = pd.read_csv("D:\日用文件\数据分析文档\little.csv",names = list("abcd"),index_col = "b")

res

a    c     d
b                 
B1   A1   C1    D1
34   12   33   ada
43   23  NaN  faes
55   44   55    da
NaN  12   33   dad

In [26]:
# 参数skiprows=[]出去选中的行数据
# 跳过的作用

res = pd.read_csv("D:\日用文件\数据分析文档\little.csv",skiprows = [0,1])

res

23    43  Unnamed: 2 faes
0  44  55.0          55   da
1  12   NaN          33  dad

In [28]:
# na_values 为指定lingyun位置为空值

res = pd.read_csv("D:\日用文件\数据分析文档\little.csv",na_values = ["lingyun"])

res 


A1   B1   C1    D1
0   12   34   33   ada
1   23   43  NaN  faes
2   44   55   55    da
3   12  NaN   33   dad
4  dad  dad   da    2r
5  dad  NaN  da1     1
6  dad  dad  NaN    12

In [48]:
# nrows读取前3行   
#                                                         默认lingyun值为空       读取前3行
#                                                   --------------------------  =========
res = pd.read_csv("D:\日用文件\数据分析文档\little.csv",na_values = ["lingyun"],nrows = 3)

res 

A1  B1    C1    D1
0  12  34  33.0   ada
1  23  43   NaN  faes
2  44  55  55.0    da

In [40]:
# 读取excel表格
# 指名sheet1表，使用默认索引
#                    读取excel表格                             表1                默认索引     从尾部开始截取掉后30行
#  ----------------------------------------------------   =================== -------------- ==============
res = pd.read_excel("D:\日用文件\数据分析文档\excel1.xls",sheet_name = "Sheet1",header = None,skipfooter = 30)
res

0   1   2   3   4   5   6   7
0  12  10  18   9  23  14  30  36
1  31   4  27  30  30  10   2  10
2   9  35  30  28  21  12   7  15
3   2  32  20  32  17  35  11  21
4   3  30  21  21  36   8   6   2
5  26  24   9   9   7  18  34   5
6  18  17  11  33  23  14  27  31
7   6  32  31  20  26   5  26  22
8  27   3  27  15  24   7  30   9

# 块读取

In [70]:
# 块读取 
# 每一条数据分为一块，一般按照为总量的1%分块
# 返回一个对象，

result = pd.read_csv("D:/日用文件/数据分析文档/little.csv",chunksize = 1)
print(result)

# 使用for循环进行遍历
for i in result:
    print(i)


   A1  B1  C1   D1
0  12  34  33  ada
   A1  B1       C1    D1
1  23  43  lingyun  faes
   A1  B1  C1  D1
2  44  55  55  da
   A1       B1  C1   D1
3  12  lingyun  33  dad
    A1   B1  C1  D1
4  dad  dad  da  2r
    A1       B1   C1  D1
5  dad  lingyun  da1   1
    A1   B1       C1  D1
6  dad  dad  lingyun  12


# to_csv

In [18]:
# to_csv 将数据框写入csv文件
import numpy as np
import pandas as pd

data1 = pd.DataFrame(np.random.randint(3,69,(5,5)),index = list("abcde"),columns = list("ABCDE"))

# 创建并写入csv文件 数据
data1.to_csv("D:/日用文件/数据分析文档/toCsv.csv")
data1


A   B   C   D   E
a  12  26  41  62  36
b  14  24  46  64   9
c  17  64  10  41  49
d  65  31  44  56  46
e  35  61  19  56  47

In [24]:
# 为某个位置元素设置空值
data2 = data1.copy()  #data1的拷贝形式

data2.loc["a","A"] = np.nan
data2.loc["e","E"] = np.nan

data2

A   B   C   D     E
a   NaN  26  41  62  36.0
b  14.0  24  46  64   9.0
c  17.0  64  10  41  49.0
d  65.0  31  44  56  46.0
e  35.0  61  19  56   NaN

In [25]:
# 创建并写入csv文件 数据
# 将空值设置为默认值
data2.to_csv("D:/日用文件/数据分析文档/toCsv2.csv",na_rep = "zhangLingYun")

data2

A   B   C   D     E
a   NaN  26  41  62  36.0
b  14.0  24  46  64   9.0
c  17.0  64  10  41  49.0
d  65.0  31  44  56  46.0
e  35.0  61  19  56   NaN

In [29]:
# 空格，空值，空字符串的区别

null_data = pd.read_csv("D:/日用文件/数据分析文档/null_1.csv")

null_data

Unnamed: 0     A     B   C    D   E
0          a    12    26  41   62  36
1          b   NaN        46    '   9
2          c    17    64  10   41  49
3          d    65    31  44   56  46
4          e          61   '  NaN  47

In [36]:
# 去掉行索引值，bool类型，  而只能保留部分列索引的值，没有bool类型
# index为FAlse，而columns的类索引只去ABC三列

null_data2 = null_data.to_csv("D:/日用文件/数据分析文档/null_2.csv",index = False,columns = ["A","B","C"])

null_data2

In [ ]:
# 为每一列自定义列名

null_data2 = null_data.to_csv("D:/日用文件/数据分析文档/null_2.csv",index = False,header = list([f"a{i}" for i in range(5)]))

null_data2


In [54]:
# 

for i in range(1,8):
    m = (r"adada%d" %i )
    l = list(m)

list(l)

['a', 'd', 'a', 'd', 'a', '7']

In [ ]:
()