# 数组的切片

In [8]:
import numpy as np

np1 = np.arange(12,20,0.05)   #生成数组，第三个参数为间隔值
# np1

In [12]:
np1 = np.random.randint(2,18,(3,6,7))
# np1

# 布尔值做索引

In [15]:
np1 = np.random.randint(2,9,5)
print(np1)

bool1 = np.array([True,False,True,False,True])    #布尔值做索引，选取为true的相对应元素
np1[bool1]

[5 6 2 5 5]


array([5, 2, 5])

In [19]:
np23 = np.arange(0,16).reshape(4,4)
print(np23)
np23[[True,False,True,False],:]    #使用bool变量进行切片
np23[[True,False,True,False],2:] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 2,  3],
       [10, 11]])

In [23]:
np1 = np.random.randint(-8,8,(6,6))
np1[np1>-7]

array([ 7,  5, -5,  1,  6,  7, -5, -6,  4, -1, -6, -1, -6, -6, -6,  3,  5,
       -1,  6, -2,  0, -6,  3,  0,  0,  4,  1, -1,  6, -6,  6, -4, -4,  7])

In [33]:
# 花式索引

import numpy as np

np1 = np.random.randint(3,60,(15,6))
np1[[2,3,4]]   #花式索引，一次选中多行

# 数组的随机筛选
np1[np.random.randint(2,8,5).tolist()]

np1[:,[2,3,4]]   #随机挑选列

array([[15, 33, 31],
       [50,  5, 25],
       [ 7, 53, 44],
       [35, 55, 57],
       [27, 48, 50],
       [44, 57, 16],
       [39,  8, 49],
       [52, 41, 24],
       [50, 57, 58],
       [ 5, 12, 46],
       [27,  7, 34],
       [ 5, 32, 35],
       [19, 35,  7],
       [11, 26, 46],
       [13, 17, 25]])

In [34]:
# 二维数组的转置就是行列元素进换位
np1 = np.random.randint(3,60,(6,6))
print(np1)
np1.T

[[26 40 13 53 16 55]
 [39 42 55 17 34 25]
 [ 7 32  6 43 30  5]
 [53 20 42 51 53 49]
 [14 50 12 31 58 53]
 [58 31 57 54  3 40]]


array([[26, 39,  7, 53, 14, 58],
       [40, 42, 32, 20, 50, 31],
       [13, 55,  6, 42, 12, 57],
       [53, 17, 43, 51, 31, 54],
       [16, 34, 30, 53, 58,  3],
       [55, 25,  5, 49, 53, 40]])

In [4]:
#高维数组的转置
import numpy as np

np_gao = np.random.randint(2,16,(2,5,5))
"""
起始外形（2,5,5）012,随数组的维度转变
"""
np_gao

array([[[ 3,  8,  6, 15,  3],
        [ 8,  4,  5, 13,  5],
        [ 7,  2, 10, 15,  7],
        [ 2, 15,  8, 15,  2],
        [13,  9,  6, 15,  4]],

       [[12,  4, 10,  3, 11],
        [14,  6,  6, 10,  5],
        [14,  7, 12, 13, 14],
        [ 5,  2,  3, 10, 10],
        [ 6, 14,  3, 11,  6]]])

In [5]:
np_gao.transpose(2,1,0)#起始位0,1,2的维度，转为2,1,0三维和一维度进行换位

array([[[ 3, 12],
        [ 8, 14],
        [ 7, 14],
        [ 2,  5],
        [13,  6]],

       [[ 8,  4],
        [ 4,  6],
        [ 2,  7],
        [15,  2],
        [ 9, 14]],

       [[ 6, 10],
        [ 5,  6],
        [10, 12],
        [ 8,  3],
        [ 6,  3]],

       [[15,  3],
        [13, 10],
        [15, 13],
        [15, 10],
        [15, 11]],

       [[ 3, 11],
        [ 5,  5],
        [ 7, 14],
        [ 2, 10],
        [ 4,  6]]])

In [9]:
# 高维数组的全转置，等价于transpose（2,1,0）函数的维度倒序，原始维度为0,1,2
np_gao.T   #高位数组的全转置

array([[[ 3, 12],
        [ 8, 14],
        [ 7, 14],
        [ 2,  5],
        [13,  6]],

       [[ 8,  4],
        [ 4,  6],
        [ 2,  7],
        [15,  2],
        [ 9, 14]],

       [[ 6, 10],
        [ 5,  6],
        [10, 12],
        [ 8,  3],
        [ 6,  3]],

       [[15,  3],
        [13, 10],
        [15, 13],
        [15, 10],
        [15, 11]],

       [[ 3, 11],
        [ 5,  5],
        [ 7, 14],
        [ 2, 10],
        [ 4,  6]]])