In [2]:
import numpy as np

In [4]:
# 用列表推导式创建一维数组
arr1 = np.array([i**2 for i in range(2,10)])
arr1

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr3 = [np.array([i**2+j for i in range(2,10)])for j in range(5)]
arr3

[array([ 4,  9, 16, 25, 36, 49, 64, 81]),
 array([ 5, 10, 17, 26, 37, 50, 65, 82]),
 array([ 6, 11, 18, 27, 38, 51, 66, 83]),
 array([ 7, 12, 19, 28, 39, 52, 67, 84]),
 array([ 8, 13, 20, 29, 40, 53, 68, 85])]

In [7]:
# 生成二维数组
arr4 = np.array([np.array([i**2+j for i in range(2,10)])for j in range(5)])
arr4

array([[ 4,  9, 16, 25, 36, 49, 64, 81],
       [ 5, 10, 17, 26, 37, 50, 65, 82],
       [ 6, 11, 18, 27, 38, 51, 66, 83],
       [ 7, 12, 19, 28, 39, 52, 67, 84],
       [ 8, 13, 20, 29, 40, 53, 68, 85]])

In [12]:
# 用一维数组创建三角函数
arr5 = np.random.randint(2,10,10)
print(arr5)
np.sin(arr5),np.cos(arr5)

[3 5 7 2 4 4 4 6 3 4]


(array([ 0.14112001, -0.95892427,  0.6569866 ,  0.90929743, -0.7568025 ,
        -0.7568025 , -0.7568025 , -0.2794155 ,  0.14112001, -0.7568025 ]),
 array([-0.9899925 ,  0.28366219,  0.75390225, -0.41614684, -0.65364362,
        -0.65364362, -0.65364362,  0.96017029, -0.9899925 , -0.65364362]))

In [36]:
import csv

x = np.linspace(-4,4,10)
f = lambda x:x**2*np.sin(x)
# np.savetext("lab.csv",(x,f(x)),delimiter=",")
print(x)
print("-"*70)
print(f(x))
print("-"*70)

# x数组和f()函数数组进行压缩,生成元组（x,f(y)）
data_zip = list(zip(x,f(x)))
data_zip

[-4.         -3.11111111 -2.22222222 -1.33333333 -0.44444444  0.44444444
  1.33333333  2.22222222  3.11111111  4.        ]
----------------------------------------------------------------------
[ 12.10883992  -0.29498554  -3.92701263  -1.7278896   -0.08492965
   0.08492965   1.7278896    3.92701263   0.29498554 -12.10883992]
----------------------------------------------------------------------


[(-4.0, 12.108839924926851),
 (-3.111111111111111, -0.29498554130218946),
 (-2.2222222222222223, -3.927012627274317),
 (-1.3333333333333335, -1.7278896024236676),
 (-0.44444444444444464, -0.08492965205498393),
 (0.44444444444444464, 0.08492965205498393),
 (1.333333333333333, 1.7278896024236663),
 (2.2222222222222214, 3.9270126272743164),
 (3.1111111111111107, 0.2949855413021937),
 (4.0, -12.108839924926851)]

In [39]:
# 写入csv文件中 
# newline参数，不让空行
with open("data.csv","w",newline="",) as f_csv:
    csv_w = csv.writer(f_csv)  # 生成一个写对象
    for data_row in data_zip:
        csv_w.writerow(data_row)

In [ ]:
# 打开music包中的data.csv文件，点击插入，生成散点图

In [46]:
# 生成一个随机数组，变成列表
arr = np.random.randint(1,100,50)
arr1 = arr.tolist()
# 将数组的每一个元素减去列表的最小值，除以列表最大值减去最小值的差
res = (arr-min(arr1))/(max(arr1)-min(arr1))
res

array([0.82474227, 0.02061856, 0.32989691, 0.50515464, 0.4742268 ,
       0.77319588, 0.08247423, 0.18556701, 0.01030928, 0.01030928,
       0.16494845, 0.22680412, 0.78350515, 0.18556701, 0.35051546,
       0.6185567 , 0.44329897, 0.64948454, 0.79381443, 1.        ,
       0.87628866, 0.12371134, 0.98969072, 0.74226804, 0.62886598,
       0.73195876, 0.30927835, 0.09278351, 0.56701031, 0.21649485,
       0.        , 0.71134021, 0.94845361, 0.03092784, 0.89690722,
       0.75257732, 0.28865979, 0.18556701, 0.29896907, 0.06185567,
       0.17525773, 0.20618557, 0.64948454, 0.28865979, 0.62886598,
       1.        , 0.7628866 , 0.18556701, 0.90721649, 0.62886598])

In [50]:
# 生成一个随机数组,并对数组元素进行计数，保存到csv中，进行画图
arr1 = np.random.randint(3,16,600)
data_index = [(index,arr1.tolist().count(index)) for index in set(arr1)]
data_index

[(3, 51),
 (4, 52),
 (5, 42),
 (6, 53),
 (7, 46),
 (8, 39),
 (9, 39),
 (10, 44),
 (11, 42),
 (12, 34),
 (13, 66),
 (14, 39),
 (15, 53)]

In [56]:
# 保存csv文件中
# csv文件中插入柱状图，漏斗筛选进行选择数据，序列一去掉进行编辑
# 选中一行数据作为参数
with open("data_index.csv","w",newline="") as f_csv:
    csv_w = csv.writer(f_csv)
    for data1 in data_index:
        csv_w.writerow(data1)

# 二维数组创建

In [62]:
# 通过嵌套列表和嵌套元组创建数组
toup1 = ((12,14,63,47),(18,19,36,45))
list1 = [[12,14,63,47],[18,19,36,45]]
arr1 = np.array(list1)
toup1 = np.array(toup1)
arr1

array([[12, 14, 63, 47],
       [18, 19, 36, 45]])

In [ ]:
# 线代数和python的维度定义是不同的

In [75]:
shap = arr1.shape  # 形状
print("二维数组形状:",shap)
size = arr1.size
print("二维数组的长度:",size)
ndim = arr1.ndim
print("维度:",ndim)
list1 = arr1.tolist()
print("转为列表:",list1)
length = len(arr1)
print("长度为{}个小数组".format(length))
type1 = arr1.dtype
print("类型为:",type1)

二维数组形状: (2, 4)
二维数组的长度: 8
维度: 2
转为列表: [[12, 14, 63, 47], [18, 19, 36, 45]]
长度为2个小数组
类型为: int32


In [77]:
# 二维数组的自动创建
# randint()函数创建，4乘6
arr1 = np.random.randint(1,25,(4,6))
arr1

array([[13,  8, 22, 15, 10,  9],
       [15, 24, 17,  3, 22, 18],
       [15,  7, 18,  9, 16, 17],
       [ 2, 11, 22, 24, 18,  1]])

In [85]:
# arange()函数创建,步数为0.1
arr2 = np.arange(1,6,0.1)
res = arr2.reshape(5,10) # 进行维度重建
res

array([[1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9]])

In [89]:
# 使用ravel函数进行拆分成一位数组
arr3 = np.random.randint(2,34,(3,5))
print(arr3)
arr3.ravel()


[[18 15 13 31 22]
 [31 16 17  5 19]
 [ 2 23  3 11 14]]


array([18, 15, 13, 31, 22, 31, 16, 17,  5, 19,  2, 23,  3, 11, 14])

In [97]:
# 产生高维数组
# 四个三维数组，一个三维数组中有5个二维数组，一个二维数组中有4x3数组
arr3 = np.random.randint(3,35,(4,5,4,3))
# arr3

In [100]:
# 生成6个为1元素的数组
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [101]:
# 生成二维数组的0元素
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [112]:
# 在二维数组中添加一列元素,加入0
arr2 = np.random.randint(3,25,(4,6))
np.array([[0] + i  for i in arr2.tolist()])

array([[ 0, 12, 11, 12, 12, 10,  9],
       [ 0,  5, 13,  8, 13, 16, 22],
       [ 0, 11, 11, 17, 10,  4, 17],
       [ 0,  4, 12,  6, 13, 22,  6]])

In [115]:
# 单位数组，只有对角线才是1，其他都是0
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [116]:
# 生成的数组，将int型转为float类型
arr3 = np.random.randint(2,34,(3,5))
arr3.astype(float)

array([[22., 24., 14., 15.,  2.],
       [26., 27., 23., 32., 29.],
       [22., 32.,  4., 17., 15.]])

In [120]:
# 根据维度形状产生0元素1元素的数组、
res1 = np.zeros_like(arr3)
res2 = np.ones_like(arr3)
print(res1)
print("-"*30)
print(res2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# 一维数组的水平拼接

In [126]:
# 一维数组的水平拼接
# hstack
arr1 = np.random.randint(2,20,10)
np.hstack((arr1,np.random.randint(-10,0,1)))

array([12, 14, 19, 18, 12, 14, 18, 10, 13,  7, -9])

In [132]:
# 一维数组与一维数组的拼接
arr1 = np.random.randint(2,20,7)
arr2 = np.random.randint(-10,0,3)
res = np.hstack((arr1,arr2))
res

array([ 3,  2,  9, 15, 19, 17, 15, -4, -6, -8])

### hstack行拼接

In [137]:
# 二维数组与二维数组的拼接
# 二维数组的拼接，行数要相等
arr3 = np.random.randint(1,10,(5,3))
arr4 = np.random.randint(-10,0,(5,4))
print(arr3)
print(arr4)
print("-"*30)
np.hstack((arr3,arr4))

[[3 3 7]
 [4 4 4]
 [1 7 4]
 [7 9 2]
 [2 1 9]]
[[-5 -6 -3 -2]
 [-1 -5 -5 -1]
 [-5 -3 -4 -7]
 [-5 -1 -8 -3]
 [-2 -2 -4 -9]]
------------------------------


array([[ 3,  3,  7, -5, -6, -3, -2],
       [ 4,  4,  4, -1, -5, -5, -1],
       [ 1,  7,  4, -5, -3, -4, -7],
       [ 7,  9,  2, -5, -1, -8, -3],
       [ 2,  1,  9, -2, -2, -4, -9]])

In [140]:
# 数组的合并
arr1 = np.random.randint(12,32,1)
arr2 = np.random.randint(12,32,1)
print(arr1,arr2)
arr1 + arr2

[16] [28]


array([44])

### vstack列拼接

In [150]:
arr3 = np.random.randint(1,10,5)
arr4 = np.random.randint(1,10,5)
print(arr3,arr4)
res = np.vstack((arr3,arr4))
res

[6 7 6 6 9] [2 1 5 5 7]


array([[6, 7, 6, 6, 9],
       [2, 1, 5, 5, 7]])

In [156]:
# 多个数组进行拼接
res = np.vstack(np.random.randint(1,36,(i,5))for i in range(1,4))
res

G:\Anaconda1\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  


array([[19,  8,  9, 10, 30],
       [33, 20, 27, 19,  7],
       [ 6, 29, 32, 32, 13],
       [32, 15,  2,  6, 25],
       [30, 33, 25, 12,  5],
       [24, 33,  1, 28, 18]])

In [160]:
# 两个数组相乘,在求和
# 内积计算
arr3 = np.random.randint(1,10,5)
arr4 = np.random.randint(1,10,5)
print(arr3,arr4)
res = sum(arr3*arr4)
res

[1 7 6 2 6] [1 3 1 1 5]


60

In [161]:
# 计算内积函数和
# 计算内积函数和
np.dot(arr3,arr4)

60

In [166]:
# numpy.random.normal(loc=0.0, scale=1.0, size=None)
# 此概率分布的标准差（对应于分布的宽度，scale越大越矮胖，scale越小，越瘦高）
arr1 = np.random.normal(6,5.3,(4,4))
# 保留两位小数
res = np.round(arr1,2)  
res


array([[ 6.2 ,  8.93,  2.07,  1.8 ],
       [-0.66,  5.72,  2.19,  8.85],
       [11.83,  2.94,  1.96,  2.28],
       [ 1.4 , 10.69,  2.65,  9.59]])

In [167]:
# 通过astype()改变数组的数据类型
res.astype(int)

array([[ 6,  8,  2,  1],
       [ 0,  5,  2,  8],
       [11,  2,  1,  2],
       [ 1, 10,  2,  9]])

In [168]:
# 通过dtype()改变数据类型
np.array(res.tolist(),dtype=str)

array([['6.2', '8.93', '2.07', '1.8'],
       ['-0.66', '5.72', '2.19', '8.85'],
       ['11.83', '2.94', '1.96', '2.28'],
       ['1.4', '10.69', '2.65', '9.59']], dtype='<U5')