In [1]:
import numpy as np

In [4]:
# arr1中存放数组，dtype控制数据类型
arr1 = np.array([12,36,47,69.4],dtype=int)
arr1


array([12, 36, 47, 69])

In [8]:
# 浮点数数，将多出一个小数点
arr1 = np.array([12,36,47,69.4],dtype=float)
res = arr1.ndim  # 返回数组的维度
print("维度为:",res)
arr1

维度为: 1


array([12. , 36. , 47. , 69.4])

In [9]:
# 二维数组
arr1 = np.array([[12,36,47,69.4]],dtype=float)
res = arr1.ndim
print("维度为:",res)
arr1

维度为: 2


array([[12. , 36. , 47. , 69.4]])

In [14]:
# shape 函数，返回数组外形
arr1 = np.array([12,36,47,69.4],dtype=float)
print("一维外形:",arr1.shape)
arr2 = np.array([[12,36,47,69.4],[12,3,47,64]],dtype=float)
print("二维外形",arr2.shape)

一维外形: (4,)
二维外形 (2, 4)


In [18]:
# size函数，返回数组的个数
arr1 = np.array([12,36,47,69.4],dtype=float)
print("一维长度:",arr1.size)
arr2 = np.array([[12,36,47,69.4],[12,3,47,64]],dtype=float)
print("二维长度:",arr2.size)

一维长度: 4
二维长度: 8


In [23]:
# tolist()函数，将数组转为列表
arr1 = np.array([12,36,47,69.4],dtype=float)
print(arr1.tolist())
arr2 = np.array([[12,36,47,69.4],[12,3,47,64]],dtype=float)
print(arr2.tolist())

[12.0, 36.0, 47.0, 69.4]
[[12.0, 36.0, 47.0, 69.4], [12.0, 3.0, 47.0, 64.0]]


In [31]:
# 一维数组的简单运算
arr3 = np.array([14,25,96,42])
arr4 = arr3*2+10
print(arr4)
res = arr4 - arr3
print(res)

[ 38  60 202  94]
[ 24  35 106  52]


In [36]:
# 二维数组的简单运算
arr2 = np.array([[12,36,47,69],[12,3,47,64]])
print(arr2)
arr2*2+1

[[12 36 47 69]
 [12  3 47 64]]


array([[ 25,  73,  95, 139],
       [ 25,   7,  95, 129]])

In [45]:
# 替换数组的值
arr3 = np.array([14,25,96,42],dtype=np.float)
arr3[2] = 12*3.11
arr3


array([14.  , 25.  , 37.32, 42.  ])

In [47]:
# 通过随机数自动生成
arr1 = np.random.randint(2,13,10)
arr1

array([ 2,  5, 12,  5,  4,  8, 11,  9,  5,  5])

In [53]:
# 生成的随机数加上随机种子seed()，每次生成的数组将不发生改变
np.random.seed(9)
arr1 = np.random.randint(2,12,10)
arr1

array([ 7,  8, 10,  8,  3,  8,  6, 10,  3, 10])

In [56]:
# 通过arange库函数生成随机数
# 参数,前开后闭,第三个参数为步长
arr2 = np.arange(1,5,0.1)
arr2

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [60]:
# 通过区间的均匀切割自动生成，第三个参数是将平均分成份数
arr3 = np.linspace(2,10,10)
arr3

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])