In [17]:
import numpy as np

a = 23 
result = np.where([type(a)==int],"整数","浮点数")
result[0]


'整数'

In [22]:
# 复杂array数组的筛选
#                 相当于条件                 value1                             value2
#          --------------------------  ========================== ------------------------------------
result = np.where([[True,False],[True,False]],[[1,2],["张凌云","王晓静"]],[["first","second"],["嘬一口","木马"]])

# result=》都是相对位置 【1，second】，【"张凌云","木马"】
result


array([['1', 'second'],
       ['张凌云', '木马']], dtype='<U11')

In [23]:
"""
如果没有后面的多余的值，将返回两个二维数组中拼凑起来true的下标的位置
"""
result = np.where([[True,False],[True,False]])
#   array(0,1)  ,  array(0,0)
result

(array([0, 1], dtype=int64), array([0, 0], dtype=int64))

In [38]:
np1 = np.random.randint(3,9,(6,6))
np1

array([[5, 8, 6, 3, 3, 7],
       [3, 5, 4, 4, 8, 4],
       [3, 8, 5, 8, 7, 6],
       [7, 3, 4, 6, 8, 4],
       [6, 6, 6, 7, 8, 3],
       [6, 7, 5, 6, 3, 3]])

In [39]:
# 挑选出6乘6的二维数组中大于5的值得下标
np1 = np.random.randint(3,9,(6,6))
np1>5

array([[False,  True, False,  True,  True, False],
       [ True,  True,  True, False, False, False],
       [False,  True,  True, False,  True,  True],
       [ True,  True, False, False, False,  True],
       [ True,  True,  True, False, False, False],
       [False, False,  True,  True, False,  True]])

In [40]:
# 生成 航与列相对位置合成的下标
np.where(np1>5)  

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5],
       dtype=int64),
 array([1, 3, 4, 0, 1, 2, 1, 2, 4, 5, 0, 1, 5, 0, 1, 2, 2, 3, 5],
       dtype=int64))

In [42]:
# 大于5的设置为True，小于5的为原始值
np.where(np1>5,"True",np1) 

array([['4', 'True', '5', 'True', 'True', '3'],
       ['True', 'True', 'True', '5', '3', '3'],
       ['3', 'True', 'True', '3', 'True', 'True'],
       ['True', 'True', '3', '3', '3', 'True'],
       ['True', 'True', 'True', '3', '3', '3'],
       ['4', '4', 'True', 'True', '3', 'True']], dtype='<U11')

In [47]:
# np.column_stac 函数进行行列转换
np3 = [np.random.randint(2,99,6) for i in range(4)]
np2 = np.column_stack(np3)
print(np2)
print(np3)

[[63 85 49 92]
 [62 43 27 91]
 [89 19 22 78]
 [ 4 26 57  4]
 [26 15 32 76]
 [84 59 65 82]]
[array([63, 62, 89,  4, 26, 84]), array([85, 43, 19, 26, 15, 59]), array([49, 27, 22, 57, 32, 65]), array([92, 91, 78,  4, 76, 82])]


In [69]:
import numpy as np 

np1 = np.random.randint(-12,24,(5000,6))
# # result = np.shape(np1)
# print(result)
# print(np1)
# np1[:,1]   #第一行的所有列

bool_ = np1[:,0] == -80
bool_.any()


False