#  一元 和二元函数


In [34]:
import numpy as np

np1 = np.random.randint(2,16,(5,5))

np.sqrt(np1)   #.sqrt函数，用于求出一个数值的平方根
np.exp(3)  #.exp函数，用于求出e（2.7。。。。。。）的n次方的值

np2 = np.random.normal(5,1.9,(5,5))   #normal函数，第一个值为取值范围，第二个函数为误差，第三个函数为矩阵形状
np.ceil(np2)  #向上取整
np.floor(np2)  #向下取整
np.sign(-12)   #取某个值的正负号

-1

In [42]:
# 二元函数
arr1 = np.random.randint(1,6,(6,6))
arr2 = np.random.randint(3,9,(6,6))
print(arr1)
print(arr2)

result1 = np.maximum(arr1,arr2)
result2 = np.minimum(arr1,arr2)
print("result1:",result1)
print("result2:",result2)

[[2 5 5 5 1 3]
 [4 5 5 5 4 4]
 [2 1 4 3 4 3]
 [1 3 1 2 4 2]
 [5 1 5 5 1 5]
 [5 2 5 2 1 4]]
[[8 6 6 5 7 3]
 [3 8 8 8 7 4]
 [8 3 7 4 8 5]
 [3 4 8 5 5 4]
 [3 4 8 6 7 5]
 [4 3 3 5 8 3]]
result1: [[8 6 6 5 7 3]
 [4 8 8 8 7 4]
 [8 3 7 4 8 5]
 [3 4 8 5 5 4]
 [5 4 8 6 7 5]
 [5 3 5 5 8 4]]
result2: [[2 5 5 5 1 3]
 [3 5 5 5 4 4]
 [2 1 4 3 4 3]
 [1 3 1 2 4 2]
 [3 1 5 5 1 5]
 [4 2 3 2 1 3]]


In [44]:
# 二元矩阵
arr1 = np.random.randint(2,6,(3,3))
arr2 = np.random.randint(2,6,(3,3))

np.power(arr1,arr2)  #power函数，以arr1矩阵为底，arr2矩阵为幂，形成新的矩阵


array([[  8,  64, 243],
       [  8,   4,   9],
       [  8, 243, 125]], dtype=int32)