In [1]:
import numpy as np

np1 = np.random.randint(1,5,(4,4))
np1

array([[2, 4, 2, 4],
       [3, 3, 3, 1],
       [1, 2, 2, 4],
       [4, 2, 2, 1]])

In [5]:
np.sum(np1,0)

array([10, 11,  9, 10])

In [13]:
result1 = np.sum(np1,0)   #当第二个参数为0是按列计算
print(result1)
result2 = np.sum(np1,1)   #当第二个参数为0是按行计算
print(result2)
result3 = np.sum(np1)
print(result3)


[10 11  9 10]
[12 10  9  9]
40


In [33]:
# 求出最小值
arr1 = np.random.randint(2,100,(5,5))
# arr2 = arr1.ravel()   #数组名.ravel（）函数，将二维数组转为一维数组
# arr2
# arr1.ravel()
print(arr1)
result1 = np.where(arr1.ravel()==np.min(arr1))[0][0]   # 返回最小值的下标值
print(result1)
result2 = np.argmin(arr1)   #返回数组最小值的下标值，等价于上面的where查询
print(result2)


[[89 69 63 43 39]
 [86 63 17 65 68]
 [88 20 59 59 43]
 [64 15 94 89 44]
 [75 13 60  4 19]]
23
23


In [45]:
# cumsum（）函数
arr2 = np.random.randint(1,9,(5,5))
print(arr2)
result1 = np.cumsum(arr2)   #连加函数，二维数组的第一个值加第二个值，得出结果再加第三个值（适用于灰度预测）
result2 = np.cumsum(arr2,0)   #同上，连加函数，逐行相加，
result2 = np.cumsum(arr2,1)   #同上，连加函数，逐列相加，
print(result2)

[[1 6 5 6 3]
 [7 8 8 2 7]
 [2 5 4 7 1]
 [4 2 4 8 3]
 [7 4 4 3 3]]
[[ 1  7 12 18 21]
 [ 7 15 23 25 32]
 [ 2  7 11 18 19]
 [ 4  6 10 18 21]
 [ 7 11 15 18 21]]


In [52]:
# cumprod（）函数，逐列，逐行，全部 相乘
arr3 = np.random.randint(1,3,(5,5))
print(arr3)
print("-"*100)
result1 = np.cumprod(arr3)
print(result1)
print("-"*100)
result2 = np.cumprod(arr3,0) #逐列相乘
print(result2)
print("-"*100)
result3 = np.cumprod(arr3,1)
print(result3)

[[1 2 1 2 2]
 [1 2 1 2 1]
 [1 2 2 2 2]
 [1 2 1 1 2]
 [1 1 2 1 1]]
----------------------------------------------------------------------------------------------------
[   1    2    2    4    8    8   16   16   32   32   32   64  128  256
  512  512 1024 1024 1024 2048 2048 2048 4096 4096 4096]
----------------------------------------------------------------------------------------------------
[[ 1  2  1  2  2]
 [ 1  4  1  4  2]
 [ 1  8  2  8  4]
 [ 1 16  2  8  8]
 [ 1 16  4  8  8]]
----------------------------------------------------------------------------------------------------
[[ 1  2  2  4  8]
 [ 1  2  2  4  4]
 [ 1  2  4  8 16]
 [ 1  2  2  2  4]
 [ 1  1  2  2  2]]
