In [7]:
import numpy as np

arr1 = np.random.randint(1,6,(5,5))
arr2 = np.random.randint(3,9,(5,5))   
print(arr1)
print(arr2)
result1 = np.intersect1d(arr1,arr2)  #数组可做集合交集
result2 = np.union1d(arr1,arr2)  #数组可做集合并集
print("result1:",result1)
print("result2:",result2)


[[5 3 1 5 3]
 [4 5 2 5 5]
 [5 5 1 1 2]
 [3 1 5 4 4]
 [5 4 4 1 3]]
[[4 6 3 6 5]
 [4 8 3 4 3]
 [6 5 5 4 4]
 [3 7 4 6 7]
 [8 8 6 5 5]]
result1: [3 4 5]
result2: [1 2 3 4 5 6 7 8]


In [22]:
# 数据的清洗practice_v1
def qingxi(arr1):
    list1 = []  #临时列表
    for i in range(len(arr1)-1):
        for j in range(i+1,len(arr1),1):  #从第i个以后的元素进行对比，步长为1
            if arr1[i] == arr1[j]:
                list1.append(j)
    return np.unique(list1)
#     return list1

arr11 = np.random.randint(3,9,15)
# arr11 = [1,2,5,8,8,9,2,8,7,2,3,4,5,8,2,6,9]
print(arr11)
result = qingxi(arr11)
print("去重后返回重复的下标值",result)

[4 5 3 5 5 8 8 4 5 3 8 5 5 6 7]
去重后返回重复的下标值 [ 3  4  6  7  8  9 10 11 12]


In [97]:
# 数据的清洗practice_v2
def qingxi2(arr):
    """
    进行数据清洗，清除去掉除去int，float类型以外的字符串
    """
    r,c = np.shape(arr)
#     print(r,c)
    for i in range(r):
        for j in range(c):
            if type(arr[i,j]) == float or type(arr[i,j]) == int:  #判断是否是int或者是float类型
                pass
            else:
                arr[i,j] = 0
    return arr


# arr22 = [[12,123,12.0],[14,23.0,23]]
for i in range(5):
    asf1[np.random.randint(1,6,1),np.random.randint(1,6,1)]
asf1
print(asf1)
qingxi2(asf1)
    
    
    
    

[[nan 10.  7.  7. nan 11.]
 [13. nan nan 12. 18.  4.]
 [nan nan nan  9. 12. 11.]
 [12. 12. nan 12. 10. nan]
 [nan 14. 15. nan nan 15.]
 [nan nan  7. nan nan nan]]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [107]:
#产生nan的数组
for i in range(5):
    asf1[np.random.randint(0,6,1),np.random.randint(0,6,1)]
asf1 

array([[ 0.,  0.,  0., nan, nan, nan],
       [nan,  0., nan,  0., nan, nan],
       [ 0., nan,  0., nan,  0.,  0.],
       [nan, nan, nan,  0.,  0., nan],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., nan, nan,  0.,  0.]])

In [123]:
arr111 = np.random.randint(0,2,(4,4))
arr = np.where(arr111==1)[1] #找到所有值为1的位置，返回数组的位置
arr.tolist()   #返回list（）列表

0

In [129]:
#数据的清洗_v3
def qingxi3(arr):
    arr_nr = list(np.where(arr == 0)[1])
    if index_j in arr_nr:
        apper_sum = arr_nr.count(index_j)
        if apper_sum>0:
            mean_1 = (arr[:,index_j].sum()/(np.shape(arr)[0]- apper_sum))
            boll = arr[:,index_j] == 0
            arr[boll,index_j] = mean_1
    return arr


In [156]:
arr_ = np.random.randint(0,3,(4,4))
# arr_ = np.random.randint(0,3,(4,4)).count(列数)   # 返回出现满足条件的次数
print(arr_)
#按列计算0列出现几个1就有几个零，1列出现几个1就有几个1,2列出现几个1就有几个2,3列出现几个1就有几个3
num = np.where(arr_ == 1)[1].tolist().count(1)   

[[2 0 2 0]
 [1 2 1 1]
 [0 1 0 1]
 [2 0 0 1]]


1