# 数据的快速挑选

In [1]:
import numpy as np

#### where数据的返回

In [2]:
# 当参数只有一个True时
np.where(True)

(array([0], dtype=int64),)

In [5]:
# True返回第一个值
np.where(True,3,-3)

array(3)

In [4]:
# False返回第二个值
np.where(False,3,-3)

array(-3)

In [6]:
# 当条件是单个的时候，后面的x，y参数的外形必须一致
np.where(False,np.array([12,45,6]),np.array([6,9,14]))

array([ 6,  9, 14])

In [7]:
# 当条件为3个bool值的时候，bool值的数量要与数组保持一致
np.where([False,False,True],np.array([12,99,3]),np.array([66,-41,-3]))

array([ 66, -41,   3])

In [8]:
# ---------
np.where([False,False,True],0,np.array([66,-41,-3]))

array([ 66, -41,   0])

In [9]:
np.where([False,False,True],99,0)

array([ 0,  0, 99])

In [11]:
# where例题
arr1 = np.random.randint(10,69,(5,5))
arr1

array([[31, 40, 17, 44, 43],
       [50, 38, 68, 29, 20],
       [14, 32, 18, 54, 43],
       [50, 41, 43, 20, 67],
       [33, 52, 15, 47, 22]])

In [15]:
(arr1>25)&(arr1<40)

array([[ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False]])

In [12]:
# 当条件为True是选着true的值，False为arr1的数据集
np.where((arr1>25)&(arr1<40),"true",arr1)

array([['true', '40', '17', '44', '43'],
       ['50', 'true', '68', 'true', '20'],
       ['14', 'true', '18', '54', '43'],
       ['50', '41', '43', '20', '67'],
       ['true', '52', '15', '47', '22']], dtype='<U11')

#### where索引的返回

In [14]:
# 当参数只有一个bool类型的时候，返回满足条件的下标值x轴，y轴
np.where((arr1>25)&(arr1<40))

(array([0, 1, 1, 2, 4], dtype=int64), array([0, 1, 3, 1, 0], dtype=int64))

## 统计函数

In [27]:
arr = np.random.randint(-4,9,(4,6))
arr

array([[ 6,  3,  3,  7,  2,  6],
       [-1,  4,  6,  8, -4,  0],
       [ 0,  6,  7,  5,  2, -4],
       [ 4,  1,  6,  8, -3, -2]])

In [28]:
# sum()函数
arr.sum()

70

In [29]:
# 验证
sum([sum(i) for i in arr.tolist()])

70

In [30]:
# 当为0时，按照每一列相加
np.sum(arr,0)

array([ 9, 14, 22, 28, -3,  0])

In [31]:
# 当为1时，按照每一行相加
np.sum(arr,1)

array([27, 13, 16, 14])

In [34]:
# 也可以写成
arr.sum(1)

array([27, 13, 16, 14])

In [35]:
arr.sum(1).astype(float)

array([27., 13., 16., 14.])

##### mean()求平均值

In [37]:
# mean()求平均值
arr1 = np.random.randint(-9,11,(4,6))
arr1

array([[ 3,  1,  0,  0,  8,  5],
       [ 1, -7,  0, -9,  6,  7],
       [-4, -9,  5, -7,  3, -2],
       [ 6, -4,  2,  7,  5,  8]])

In [38]:
arr1.mean()

1.0416666666666667

In [48]:
# 拆解
sum([sum(i) for i in arr1.tolist()])/len(np.ravel(arr1))

1.0416666666666667

In [49]:
# 按列求平均值
np.mean(arr1,0)

array([ 1.5 , -4.75,  1.75, -2.25,  5.5 ,  4.5 ])

In [50]:
# 按行求平均值
np.mean(arr1,1)

array([ 2.83333333, -0.33333333, -2.33333333,  4.        ])

##### argmin()和argmax()函数

In [55]:
arr1 = np.random.randint(-9,11,(4,6))
arr1

array([[-6,  1,  4,  0,  5, -9],
       [ 1,  0,  8, -1, -2,  9],
       [ 3, -8, -5,  8,  9,  6],
       [-6, 10,  0, -9, -5,  1]])

In [56]:
# 返回成一维数组的下标值
np.argmin(arr1)

5

In [65]:
# 拆解，将一维数组中等于最小值的值为True
arr1.ravel()==np.min(arr1.ravel())

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False])

In [68]:
# 拆解
np.where(arr1.ravel()==np.min(arr1.ravel()))[0][0]

5

In [69]:
# 返回每一列中最小值的列号
np.argmin(arr1,0)

array([0, 2, 2, 3, 3, 0], dtype=int64)

In [70]:
# 返回每一行中最小值的列号
np.argmin(arr1,1)

array([5, 4, 1, 3], dtype=int64)

#### cumsum()累加

In [74]:
np.cumsum(arr1)

array([-6, -5, -1, -1,  4, -5, -4, -4,  4,  3,  1, 10, 13,  5,  0,  8, 17,
       23, 17, 27, 27, 18, 13, 14], dtype=int32)

In [75]:
np.cumsum(arr1,1)

array([[ -6,  -5,  -1,  -1,   4,  -5],
       [  1,   1,   9,   8,   6,  15],
       [  3,  -5, -10,  -2,   7,  13],
       [ -6,   4,   4,  -5, -10,  -9]], dtype=int32)

In [76]:
# cumprod()累乘
np.cumprod(arr1)

array([ -6,  -6, -24,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32)

In [79]:
np.cumprod(arr1,1)

array([[   -6,    -6,   -24,     0,     0,     0],
       [    1,     0,     0,     0,     0,     0],
       [    3,   -24,   120,   960,  8640, 51840],
       [   -6,   -60,     0,     0,     0,     0]], dtype=int32)

### 方差精简公式

In [85]:
"""
x上面有一个横线。
这个符号念做“X bar”，为求平均值符号。
### 平均值有，算术平均值，几何平均值，平方平均值，调和平均值，加权平均值等几种
例如，某企业生产A产品10台，单价100元；生产B产品5台，单价50元；生产C产品3台，单价30元，计算平均价格？
简单平均法：平均价格=∑各类产品单价 /  产品种类   平均价格=（100+50+30）/ 3 = 60（元）
加权平均法：平均价格=∑（产品单价×产品数量）/ ∑（产品数量）平均价格=（100×10+50×5+30×3）/（10+5+3）= 74.44（元）
可以看出，简单平均与加权平均计算出来的平均值差距较大，而后者更贴近事实，属于精确计算。
"""
print(" ")

In [ ]:
"""
∑ 是一个求和符号，英语名称：Sigma，汉语名称：西格玛（大写Σ，小写σ）
大写Σ用于数学上的总和符号，比如：∑Pi，其中i=1,2,...,T，即为求P1 + P2 + ... + PT的和。
小写σ用于统计学上的标准差。西里尔字母的С及拉丁字母的S都是由Sigma演变而成。
"""

In [ ]:

# 方差精简公式1
# 当一组数据为n个
s**2 = 1/n * [()]

# 310节没有学习

In [94]:
arr1 = np.random.randint(10,99,(4,5))
print(arr1.sum())
arr1

1195


array([[23, 61, 77, 21, 19],
       [81, 41, 45, 72, 96],
       [11, 98, 14, 97, 35],
       [93, 94, 72, 59, 86]])

In [95]:
# 返回True和False
(arr1>20)&(arr1<50)

array([[ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [96]:
# 按每一列进行计算
arr1.sum(0)

array([208, 294, 208, 249, 236])

In [97]:
# 按每一行进行计算
arr1.sum(1)

array([201, 335, 255, 404])

In [100]:
bool_arr1 = (arr1>20)&(arr1<50)
bool_arr1

array([[ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [101]:
# 将布尔类型改为int类型
bool_arr1.astype(int)

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [106]:
# any()函数判断数据集合中是否含有True值

bool_arr1.any()

True

In [107]:
# all()函数判断数据集合中是否全部都是True值

bool_arr1.all()

False