In [3]:
import numpy as np

In [13]:
# 实战
# 第二题
# 中位数补值
# 生成一个随机含有空值的数据集
arr2 = np.random.randint(12,50,(8,5)).astype(float)
arr2

array([[49., 28., 45., 39., 27.],
       [13., 34., 12., 37., 49.],
       [39., 12., 14., 21., 39.],
       [37., 37., 25., 48., 40.],
       [25., 34., 23., 20., 39.],
       [35., 17., 39., 35., 48.],
       [48., 44., 39., 26., 21.],
       [17., 42., 20., 39., 46.]])

In [19]:
arr2[np.random.randint(0,8,5),np.random.randint(0,5,5)] = np.nan
arr2

array([[49. , 28. , 45. , 31.5, 27. ],
       [13. , 34. ,  nan, 37. , 49. ],
       [ nan, 12. , 14. , 21. , 39. ],
       [37. , 37. , 25. , 48. , 40. ],
       [25. , 34. , 23. , 20. , 39. ],
       [35. ,  nan, 39. , 31.5, 48. ],
       [48. , 44. ,  nan, 26. , 40. ],
       [37. , 34. ,  nan, 39. , 46. ]])

In [28]:
def fillup2(arr3):
    # 判断，返回含有空值的布尔类型数据集
    arr2_bool = np.isnan(arr3)
    index_list = []
    r,c = arr3.shape
    for col in range(c):
        for row in range(r):
            if arr2_bool[row,col]:
                index_list.append((row,col))
    for indices in index_list:
        row2,col2 = indices
        arr3[row2,col2] = np.median(arr3[:,col2][~np.isnan(arr3[:,col2])])
    
    return arr3

In [29]:
fillup2(arr2)

array([[49. , 28. , 45. , 31.5, 27. ],
       [13. , 34. , 25. , 37. , 49. ],
       [37. , 12. , 14. , 21. , 39. ],
       [37. , 37. , 25. , 48. , 40. ],
       [25. , 34. , 23. , 20. , 39. ],
       [35. , 34. , 39. , 31.5, 48. ],
       [48. , 44. , 25. , 26. , 40. ],
       [37. , 34. , 25. , 39. , 46. ]])

In [31]:
# 实战第三题
# 参数为，中心轴为2.6，散度为2.1，
data_normal = np.random.normal(2.6,2.1,2000)
data_normal

array([4.60888315, 1.10399749, 3.17727287, ..., 5.69811122, 5.79458201,
       3.46591822])

In [49]:
# 参数为数据集，和组数
def group1(data,m):
    infor_group = []
    list_random = data.tolist()
    # 列表最大值减去最小值除去份数，得出组距
    intev = (max(list_random)-min(list_random))/m
    data_split = [min(list_random)+n*(intev+0.001)for n in range(m+1)]
    for bound in range(len(data_split)-1):
        infor_group.append([str(round(data_split[bound],5))+"-->"+str(round(data_split[bound],5)),
            (((data>=data_split[bound]) & (data<data_split[bound+1])).tolist()).count(True)])
        
    return infor_group
     

In [51]:
group1(data_normal,10)

[['-4.43359-->-4.43359', 7],
 ['-2.97114-->-2.97114', 39],
 ['-1.5087-->-1.5087', 165],
 ['-0.04625-->-0.04625', 377],
 ['1.4162-->1.4162', 498],
 ['2.87864-->2.87864', 502],
 ['4.34109-->4.34109', 285],
 ['5.80354-->5.80354', 101],
 ['7.26598-->7.26598', 22],
 ['8.72843-->8.72843', 4]]

In [53]:
# 实战习题3
# 计算阶乘
# 阶乘1乘2乘3乘4
from functools import reduce

def jiecheng(n):
    if n == 0:
        return 1
    else:
        result = reduce(lambda x,y :x*y,range(1,n+1))
        return result
    
jiecheng(4)

24

In [54]:
# 参数：函数类型，某值，m
def series(formula,range_x,m):
    x1 = np.linspace(-range_x,range_x,5000)
    if formula == 0:
        return sum([((x1**(2*n+1))/jiecheng(2*n+1))*((-1)**n) for n in range(m)])
    else:
        return sum([((x1**(2*n))/jiecheng(2*n))*((-1)**n) for n in range(m)])


In [59]:
# 做成可以下载的数据
x_v = np.linspace(-8,8,5000)
data_list1 = []
data_list2 = []
for m in range(1,12,2):
    ser1 = series(0,8,m).tolist()
    data_list1.append(ser1)
    ser2 = series(0,8,m).tolist()
    data_list2.append(ser2)
 
data1 = np.vstack((x_v,np.array(data_list1))).T
data2 = np.vstack((x_v,np.array(data_list2))).T
data1

array([[  -8.        ,   -8.        , -195.73333333, ...,  -22.58937836,
          -2.01415186,   -1.00996199],
       [  -7.99679936,   -7.99679936, -195.28670653, ...,  -22.46409273,
          -2.00696273,   -1.01023547],
       [  -7.99359872,   -7.99359872, -194.84087092, ...,  -22.3394767 ,
          -1.99981745,   -1.01050043],
       ...,
       [   7.99359872,    7.99359872,  194.84087092, ...,   22.3394767 ,
           1.99981745,    1.01050043],
       [   7.99679936,    7.99679936,  195.28670653, ...,   22.46409273,
           2.00696273,    1.01023547],
       [   8.        ,    8.        ,  195.73333333, ...,   22.58937836,
           2.01415186,    1.00996199]])