# 数组的转置day01

In [1]:
# 数组的转置
import numpy as np

In [3]:
# randn函数返回一个或一组样本，具有标准正态分布。
# dn表格每个维度
# 返回值为指定维度的array
arr1 = np.random.randn(3,4)
arr1

array([[-0.71285458,  1.23468268, -1.14376342,  0.63195286],
       [-1.14022751, -0.00642247,  0.68278044,  0.36845138],
       [-0.69491152,  0.24957828,  0.96666805, -0.00912048]])

In [4]:
# 二维数组的转置
arr1.T

array([[-0.71285458, -1.14022751, -0.69491152],
       [ 1.23468268, -0.00642247,  0.24957828],
       [-1.14376342,  0.68278044,  0.96666805],
       [ 0.63195286,  0.36845138, -0.00912048]])

### 高维数组的转置

In [5]:
# 高维数组的转置
# 转置就是把轴序列任意两个索引值进行交换一次
arr2 = np.random.randint(11,99,(3,5,4))
arr2

array([[[28, 19, 29, 47],
        [61, 32, 31, 53],
        [46, 87, 46, 25],
        [46, 62, 43, 44],
        [76, 49, 60, 72]],

       [[46, 32, 74, 55],
        [35, 65, 70, 68],
        [66, 70, 40, 50],
        [61, 89, 36, 68],
        [44, 45, 23, 98]],

       [[42, 98, 37, 25],
        [43, 46, 51, 82],
        [53, 59, 39, 76],
        [60, 75, 11, 81],
        [33, 98, 51, 60]]])

In [6]:
# 返回的轴序列就是shape返回的索引编号序列0，1，2
arr2.shape

(3, 5, 4)

In [8]:
# 一次转置和二次转置，造成数据的外形发生改变和，每个元素的索引改变
# (0,1,2) -->(2,1,0) 元素的坐标也将随着转置规律发生改变
# 全转置倒叙转置
# 四维数组shape的索引序号序列的为0，1，2，3
arr2.transpose(2,1,0)

array([[[28, 46, 42],
        [61, 35, 43],
        [46, 66, 53],
        [46, 61, 60],
        [76, 44, 33]],

       [[19, 32, 98],
        [32, 65, 46],
        [87, 70, 59],
        [62, 89, 75],
        [49, 45, 98]],

       [[29, 74, 37],
        [31, 70, 51],
        [46, 40, 39],
        [43, 36, 11],
        [60, 23, 51]],

       [[47, 55, 25],
        [53, 68, 82],
        [25, 50, 76],
        [44, 68, 81],
        [72, 98, 60]]])

### 一元常用函数

In [12]:
arr1 = np.random.randint(9,63,(4,4))
arr1

array([[30, 36, 14, 52],
       [27, 59, 52, 29],
       [43, 32, 19,  9],
       [31, 47, 33, 34]])

In [13]:
# 一元函数的开放
np.sqrt(arr1)

array([[5.47722558, 6.        , 3.74165739, 7.21110255],
       [5.19615242, 7.68114575, 7.21110255, 5.38516481],
       [6.55743852, 5.65685425, 4.35889894, 3.        ],
       [5.56776436, 6.8556546 , 5.74456265, 5.83095189]])

In [14]:
# 求exe^{x}e 
# 一元函数的exp函数
np.exp(arr1)


array([[1.06864746e+13, 4.31123155e+15, 1.20260428e+06, 3.83100800e+22],
       [5.32048241e+11, 4.20121040e+25, 3.83100800e+22, 3.93133430e+12],
       [4.72783947e+18, 7.89629602e+13, 1.78482301e+08, 8.10308393e+03],
       [2.90488497e+13, 2.58131289e+20, 2.14643580e+14, 5.83461743e+14]])

In [16]:
arr2 = np.random.randint(-9,0,(4,4))
arr2

array([[-8, -6, -8, -2],
       [-6, -6, -5, -4],
       [-6, -1, -7, -4],
       [-3, -4, -3, -9]])

In [17]:
# 取绝对值函数
np.abs(arr2)

array([[8, 6, 8, 2],
       [6, 6, 5, 4],
       [6, 1, 7, 4],
       [3, 4, 3, 9]])

In [21]:
arr3 = np.random.normal(2,2.3,(4,4))
arr3

array([[ 3.25377894,  0.75639376, -3.05748816,  5.01044451],
       [ 3.86146348,  3.47149915,  5.70410324,  4.82293748],
       [ 0.24248089,  2.96878278,  0.60697835,  4.3994074 ],
       [-0.7390649 ,  2.63796613, -0.44118209,  2.51835323]])

In [22]:
# 向下取整函数
np.floor(arr3)

array([[ 3.,  0., -4.,  5.],
       [ 3.,  3.,  5.,  4.],
       [ 0.,  2.,  0.,  4.],
       [-1.,  2., -1.,  2.]])

In [23]:
# 向上取整ceil
np.ceil(arr3)

array([[ 4.,  1., -3.,  6.],
       [ 4.,  4.,  6.,  5.],
       [ 1.,  3.,  1.,  5.],
       [-0.,  3., -0.,  3.]])

In [24]:
# sign函数，正数返回+1，负数返回-1
np.sign(arr3)

array([[ 1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [-1.,  1., -1.,  1.]])

### 二元函数

In [27]:
# 比较两个数据集的大小，返回大值的函数maximum
# 同理，minimum()函数，取出两个数据集中的最小值
arr1 = np.random.randint(1,36,(4,4))
arr2 = np.random.randint(1,36,(4,4))
np.maximum(arr1,arr2)
# np.minimum(arr1,arr2)

array([[27, 22, 16, 16],
       [28,  9, 32, 30],
       [34, 27, 20, 22],
       [12, 29, 20, 33]])

In [28]:
# 加减乘除函数
np.add(arr1,arr2)
np.subtract(arr1,arr2)
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
# 以参数1为底，参数2为幂,要避免值的溢出
np.power(arr1,arr2)

array([[0.66666667, 0.45454545, 0.9375    , 0.6875    ],
       [0.21428571, 3.        , 0.5625    , 1.76470588],
       [0.05882353, 0.66666667, 1.66666667, 0.04545455],
       [6.        , 0.48275862, 2.        , 1.03125   ]])

#### 产生一个坐标群

In [32]:
# 产生一个坐标点
x = np.arange(-3,4)
y = np.arange(-2,5)
print(x)
print(y)

[-3 -2 -1  0  1  2  3]
[-2 -1  0  1  2  3  4]


In [34]:
# 使用meshgrid()函数
sx,sy = np.meshgrid(x,y)
print(sx)
sy

[[-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]
 [-3 -2 -1  0  1  2  3]]


array([[-2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4]])

In [41]:
# 使用ravel()函数将两个数据集进行展开为一维数组
np.ravel(sx)

array([-3, -2, -1,  0,  1,  2,  3, -3, -2, -1,  0,  1,  2,  3, -3, -2, -1,
        0,  1,  2,  3, -3, -2, -1,  0,  1,  2,  3, -3, -2, -1,  0,  1,  2,
        3, -3, -2, -1,  0,  1,  2,  3, -3, -2, -1,  0,  1,  2,  3])

In [46]:
# 将两个数据集进行压缩
res_zip = zip(np.ravel(sx),np.ravel(sy))
# list(res_zip)

In [47]:
# 写入csv
import csv

with open("dian.csv","w",newline="",) as f_csv:
    csv_w = csv.writer(f_csv)  # 生成一个写对象
    for res_row in res_zip:
        csv_w.writerow(res_row)