# 数组元素的切片与索引

In [2]:
# 数组元素的切片与索引
import numpy as np

In [22]:
arr1 = np.random.randint(3,36,10)
arr1

array([ 9, 11,  3, 26, 24, 11, 26, 13, 31, 13])

### 一维数组的切片

In [50]:
# 一维数组的索引切片
arr2 = np.random.randint(2,36,10)
print(arr2)
arr2[1:5] = [111,222,333,444]
arr2

[31 21  7  3 32 22  7  5 33 29]


array([ 31, 111, 222, 333, 444,  22,   7,   5,  33,  29])

In [45]:
arr1[-1:2:-1]

array([13, 31, 13, 26, 11, 24, 26])

In [52]:
arr2 = np.random.randint(2,36,10)
print(arr2)
arr2[-1:6:-1] = np.array([999,888,777])
arr2

[26 31 18 15 19 16 13 13 19  9]


array([ 26,  31,  18,  15,  19,  16,  13, 777, 888, 999])

### 二维数组的切片

#### 二维数组的下标

In [60]:
arr1 = np.random.randint(12,69,(4,5))
arr1

array([[36, 66, 26, 23, 32],
       [64, 21, 34, 54, 13],
       [68, 44, 67, 49, 46],
       [68, 12, 18, 40, 31]])

In [57]:
# 第一个值为负数的时候，为负行开始
arr1[-1,2]   # -1行2列

13

In [59]:
# 第一个值为正，行与列都从零开始
arr1[2,2]

64

In [62]:
# 二维数组的行选区
arr1 = np.random.randint(12,69,(4,5))
arr1

array([[49, 32, 31, 15, 17],
       [60, 41, 56, 50, 50],
       [29, 61, 51, 61, 17],
       [12, 46, 39, 65, 27]])

In [63]:
arr1[2]

array([29, 61, 51, 61, 17])

In [65]:
# 二维数组的列选区
arr1[:,2]

array([31, 56, 51, 39])

In [69]:
arr1[1:,2]

array([56, 51, 39])

In [70]:
arr1[1:2,2]

array([56])

In [75]:
# reshape进行维度重建
arr1[:,2].reshape(2,2)

array([[31, 56],
       [51, 39]])

In [76]:
arr1[:,2].reshape(len(arr1[:,2]),1)

array([[31],
       [56],
       [51],
       [39]])

In [78]:
# 二维数组的一般选区
arr1[1:3,2:4]

array([[56, 50],
       [51, 61]])

In [81]:
# 二维数组的赋值
# 二维数组的赋值必定会破坏原数组
arr1 = np.random.randint(12,69,(5,5))
arr1

array([[40, 49, 23, 41, 58],
       [61, 49, 48, 32, 63],
       [61, 66, 47, 53, 65],
       [43, 57, 15, 36, 41],
       [38, 27, 55, 42, 43]])

In [84]:
arr1[3,3] = 9999
arr1

array([[  40,   49,   23,   41,   58],
       [  61,   49,   48,   32,   63],
       [  61,   66,   47,   53,   65],
       [  43,   57,   15, 9999,   41],
       [  38,   27,   55,   42,   43]])

In [88]:
# 二维数组的选区赋值
arr1[:,2] = 999
arr1

array([[  40,   49,  999,   41,   58],
       [  61,   49,  999,   32,   63],
       [  61,   66,  999,   53,   65],
       [  43,   57,  999, 9999,   41],
       [  38,   27,  999,   42,   43]])

In [91]:
arr1[1:3,2:4] = 0
arr1

array([[  40,   49,  999,   41,   58],
       [  61,   49,    0,    0,   63],
       [  61,   66,    0,    0,   65],
       [  43,   57,  999, 9999,   41],
       [  38,   27,  999,   42,   43]])

In [101]:
# 嵌套列表的替换
# 将二维数组改为object型，方便插入字符
arr1 = np.random.randint(12,69,(5,5)).astype(object)
arr1

array([[55, 52, 67, 14, 38],
       [17, 21, 23, 41, 55],
       [20, 26, 48, 33, 37],
       [14, 50, 40, 65, 57],
       [39, 16, 15, 19, 36]], dtype=object)

In [103]:
arr1[1:3,2:4] = [[999,999],[666,666]]
arr1

array([[55, 52, 67, 14, 38],
       [17, 21, 999, 999, 55],
       [20, 26, 666, 666, 37],
       [14, 50, 40, 65, 57],
       [39, 16, 15, 19, 36]], dtype=object)

In [106]:
arr1[3:,0:2] = [["M","M"],["T","T"]]
arr1

array([[55, 52, 67, 14, 38],
       [17, 21, 999, 999, 55],
       [20, 26, 666, 666, 37],
       ['M', 'M', 40, 65, 57],
       ['T', 'T', 15, 19, 36]], dtype=object)

In [109]:
# 三维数组的索引与选取
# 创建三维数组，参数为3个二维数组，一个二维数组有4行4列
arr2 = np.random.randint(10,99,(3,4,4))
arr2

array([[[39, 10, 56, 50],
        [55, 45, 72, 67],
        [53, 64, 79, 77],
        [25, 64, 26, 15]],

       [[96, 76, 62, 82],
        [38, 92, 21, 16],
        [83, 58, 50, 96],
        [20, 21, 54, 72]],

       [[90, 76, 87, 19],
        [71, 45, 28, 66],
        [48, 73, 73, 72],
        [82, 71, 43, 37]]])

In [115]:
# 三维数组的选取
# 参数为第一个二维数组，第一行第一列的值
arr2[1,1,1]

92

In [116]:
# 先选出为1的二维数组
arr2[1]

array([[96, 76, 62, 82],
       [38, 92, 21, 16],
       [83, 58, 50, 96],
       [20, 21, 54, 72]])

In [117]:
# 再通过下标值选择
arr2[1][1,1]

92

In [122]:

arr2[2][:,2:3]

array([[87],
       [28],
       [73],
       [43]])

In [125]:
# bool类型替代
bool1 = np.array([False,True,False,True,False])
arr1 = np.random.randint(11,36,(5,5))
arr1

array([[27, 25, 21, 19, 11],
       [34, 14, 24, 14, 22],
       [32, 19, 15, 20, 34],
       [15, 12, 28, 23, 12],
       [27, 21, 35, 27, 26]])

In [126]:
# 使用bool1类型进行替换行
# 取出行数为True的行
arr1[bool1]

array([[34, 14, 24, 14, 22],
       [15, 12, 28, 23, 12]])

In [127]:
# 使用bool1替换列
# 取出列数为true的列
arr1[:,bool1]

array([[25, 19],
       [14, 14],
       [19, 20],
       [12, 23],
       [21, 27]])

In [131]:
# 自动产生bool数组
arr2 = np.random.randint(10,150,(9,9))
arr2

array([[ 18,  51,  38,  94, 145,  59,  59,  91,  52],
       [121,  66, 126,  14,  55, 138,  54, 139,  35],
       [112, 122,  78, 113, 105, 110, 134,  67,  14],
       [ 68, 108,  93,  21,  64,  38,  67, 134,  34],
       [121,  89,  76,  22, 121,  40, 128,  20,  56],
       [ 55,  92,  78,  34,  73,  81, 112,  61, 108],
       [ 11,  79,  95, 130,  78,  97,  39,  83,  75],
       [ 91,  44,  76, 143, 148, 145,  80,  21,  23],
       [ 47,  26,  94,  12,  52, 135,  53,  35,  46]])

In [132]:
# 筛选出大于100的值，
# 得到bool数组
arr2>100

array([[False, False, False, False,  True, False, False, False, False],
       [ True, False,  True, False, False,  True, False,  True, False],
       [ True,  True, False,  True,  True,  True,  True, False, False],
       [False,  True, False, False, False, False, False,  True, False],
       [ True, False, False, False,  True, False,  True, False, False],
       [False, False, False, False, False, False,  True, False,  True],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False,  True,  True,  True, False, False, False],
       [False, False, False, False, False,  True, False, False, False]])

In [134]:
# 将得到的bool数组放到索引位置
# 刷选出大于100的值
arr2[arr2>100]

array([145, 121, 126, 138, 139, 112, 122, 113, 105, 110, 134, 108, 134,
       121, 121, 128, 112, 108, 130, 143, 148, 145, 135])

In [142]:
# 扩展，广播功能再计算中的作用
arr3 = np.random.randint(2,9,(5,5))
arr4 = np.random.randint(2,9,5)
arr5 = np.random.randint(2,9,(2,5))
print(arr5)
print("-"*30)
print(arr4)
arr3

[[7 5 5 7 3]
 [8 3 5 3 4]]
------------------------------
[7 3 3 5 7]


array([[7, 4, 4, 8, 8],
       [5, 7, 7, 2, 5],
       [5, 6, 3, 2, 2],
       [6, 8, 4, 4, 2],
       [8, 5, 5, 8, 4]])

In [139]:
# 一维数组与二维数组的相乘
# 单行乘以多行，且不能多行诚意不相等的行数
arr3*arr4

array([[56, 12, 16, 30, 12],
       [28, 14, 16, 40, 12],
       [49, 12, 20, 25, 16],
       [35,  4, 28, 20, 10],
       [28, 16, 24, 15,  4]])

In [145]:
arr = arr3[:,1:2]
arr

array([[4],
       [7],
       [6],
       [8],
       [5]])

In [146]:
# 列与列的相乘
arr3*arr

array([[28, 16, 16, 32, 32],
       [35, 49, 49, 14, 35],
       [30, 36, 18, 12, 12],
       [48, 64, 32, 32, 16],
       [40, 25, 25, 40, 20]])

In [148]:
# 拓展，花式索引
# 多行选区
arr = np.random.randint(11,99,(11,11))
arr


array([[69, 95, 68, 44, 87, 55, 32, 19, 47, 46, 81],
       [49, 39, 39, 43, 14, 13, 52, 92, 62, 78, 95],
       [25, 97, 55, 47, 32, 98, 89, 32, 58, 26, 97],
       [85, 92, 22, 47, 58, 60, 30, 81, 72, 86, 73],
       [25, 33, 79, 67, 43, 36, 11, 80, 94, 50, 40],
       [69, 23, 13, 70, 38, 42, 97, 12, 49, 35, 47],
       [34, 18, 70, 13, 45, 71, 23, 55, 75, 85, 85],
       [61, 94, 26, 98, 87, 42, 71, 47, 43, 37, 28],
       [57, 67, 71, 49, 27, 53, 83, 60, 23, 61, 56],
       [50, 97, 54, 80, 19, 40, 47, 74, 30, 21, 76],
       [16, 23, 78, 58, 48, 95, 64, 17, 56, 48, 55]])

In [149]:
# 多行选取
arr[[0,2,4],:]

array([[69, 95, 68, 44, 87, 55, 32, 19, 47, 46, 81],
       [25, 97, 55, 47, 32, 98, 89, 32, 58, 26, 97],
       [25, 33, 79, 67, 43, 36, 11, 80, 94, 50, 40]])

In [150]:
# 多列选取
arr[:,[0,2,3]]

array([[69, 68, 44],
       [49, 39, 43],
       [25, 55, 47],
       [85, 22, 47],
       [25, 79, 67],
       [69, 13, 70],
       [34, 70, 13],
       [61, 26, 98],
       [57, 71, 49],
       [50, 54, 80],
       [16, 78, 58]])

In [161]:
# 精确选取
# 选取0,1,2行下的，所有行下的0,1列
arr[[0,1,2]][:,[0,1]]

array([[69, 95],
       [49, 39],
       [25, 97]])

### 空值在numpy中的表示

In [163]:
arr4 = np.array([[np.nan,6,9],[3,np.nan,9]])
arr4

array([[nan,  6.,  9.],
       [ 3., nan,  9.]])

In [166]:
# np.isnan()判断是否为空值，返回为bool型
np.isnan(arr4)

array([[ True, False, False],
       [False,  True, False]])

In [169]:
# 将返回的布尔类型返回为nan值
arr4[np.isnan(arr4)]

array([nan, nan])

In [171]:
arr4[np.isnan(arr4)][0]

nan

#### 值的筛选

In [173]:
# 值的筛选
arr5 = np.random.randint(11,99,(20))
arr5

array([20, 22, 14, 14, 86, 55, 11, 76, 22, 94, 22, 57, 95, 47, 11, 78, 85,
       73, 22, 47])

In [175]:
# 得到布尔类型的数组
arr5>50

array([False, False, False, False,  True,  True, False,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
       False, False])

In [176]:
# 将布尔类型的数组放到索引位置
# 得出arr5数组中大于50的值
arr5[arr5>50]

array([86, 55, 76, 94, 57, 95, 78, 85, 73])

### 实战题目

In [178]:
# 创建数组，-1值附近，散度为2.6，8乘8，保留两位小数
# 需求：判断第二列中受否有-6.53和-0.04的值，如果有，将两行打印出来
arr1 = np.round(np.random.normal(-1,2.6,(8,8)),2)
arr1

array([[ 3.18,  3.2 , -5.8 , -2.21,  1.85, -3.03,  1.03, -0.79],
       [-1.72, -6.53,  2.86, -1.93, -0.51,  0.67,  3.41,  1.44],
       [-1.74,  1.55, -3.78, -2.27, -0.21,  2.99,  5.72, -1.52],
       [ 3.38,  0.67,  0.68, -5.46, -5.86,  0.64,  0.36, -0.77],
       [ 1.36,  1.54,  4.62, -3.51, -5.66,  0.48, -5.39,  1.64],
       [ 0.77, -1.61, -2.85, -3.35, -3.07,  0.07,  3.43, -0.78],
       [ 0.14, -0.04, -5.46, -0.15, -5.2 ,  1.8 , -6.75, -4.98],
       [ 1.74, -1.75,  1.37, -2.68,  2.99,  2.57,  2.06,  1.98]])

In [188]:
# 进行判断是否有值
# 返回的有true值，代表存在
arr1[:,1]==-6.53

array([False,  True, False, False, False, False, False, False])

In [189]:
arr1[(arr1[:,1]==-6.53) | (arr1[:,1]==-0.04)]

array([[-1.72, -6.53,  2.86, -1.93, -0.51,  0.67,  3.41,  1.44],
       [ 0.14, -0.04, -5.46, -0.15, -5.2 ,  1.8 , -6.75, -4.98]])

In [198]:
# 第二题
# 中位数补值
# 生成一个随机含有空值的数据集
arr2 = np.random.randint(12,50,(8,5)).astype(float)
arr2

array([[27., 13., 29., 49., 17.],
       [46., 25., 39., 46., 25.],
       [18., 22., 45., 19., 44.],
       [34., 17., 29., 48., 21.],
       [23., 20., 21., 30., 29.],
       [44., 42., 19., 40., 35.],
       [15., 18., 38., 26., 42.],
       [22., 35., 34., 26., 15.]])

In [227]:
# 产生随机的空值
arr2[np.random.randint(0,8,5),np.random.randint(0,5,5)] = np.nan
arr2

array([[nan, 13., nan, nan, 17.],
       [46., 25., 39., nan, nan],
       [18., nan, 45., 19., 44.],
       [34., 17., nan, nan, 21.],
       [23., 20., 21., nan, nan],
       [nan, 42., 19., 40., 35.],
       [15., 18., nan, nan, 42.],
       [nan, 35., 34., nan, 15.]])

In [222]:
# 先判断是否有空值,返回bool类型，空值为True
# np.isnan(arr2)

# shape 函数返回数据集的维度，
# c,r = arr2.shape

In [241]:
def fillup(arr3):
    # 判断，返回含有空值的布尔类型数据集
    arr2_bool = np.isnan(arr3)
    index_list = []
    r,c = arr3.shape
    for col in range(c):
        for row in range(r):
            if arr2[row,col] == True:
                index_list.append((row,col))
                print(index_list)
    for indices in index_list:
        print("sdwad")
        print(indices)
        row2,col2 = indices
        arr[row2,col2] = np.median(arr[:,col2][~np.isnan(arr[:,col2])])
    
    return arr3
                

In [243]:
fillup(arr2)

array([[nan, 13., nan, nan, 17.],
       [46., 25., 39., nan, nan],
       [18., nan, 45., 19., 44.],
       [34., 17., nan, nan, 21.],
       [23., 20., 21., nan, nan],
       [nan, 42., 19., 40., 35.],
       [15., 18., nan, nan, 42.],
       [nan, 35., 34., nan, 15.]])