In [45]:
import numpy as np

def row_and_column(arr1,arr2):
    """
    两个矩阵相乘，first
    算法与编程
    """
    if arr1.shape[1] != arr2.shape[0]:
        return "矩阵1和矩阵2的行和列不相等！"
    r = arr1.shape[0];c = arr2.shape[1]    #确定矩阵1的行和第二矩阵的列数
    null_m = np.zeros((r,c))
    for i in range(r):
        for j in range(c):
            null_m[i,j] = sum([arr1[i,k]*arr2[k,j] for k in range(arr1.shape[1])])
    return null_m
    

arr1 = np.random.randint(1,4,(2,2))
print(arr1)
arr2 = np.random.randint(0,3,(2,2))
print(arr2)

row_and_column(arr1,arr2)


[[1 3]
 [2 3]]
[[0 0]
 [2 1]]


array([[6., 3.],
       [6., 3.]])

In [46]:
# 两个矩阵相乘,second
arr1@arr2

array([[6, 3],
       [6, 3]])

In [50]:
# 两个矩阵相乘 third
np.dot(arr1,arr2)

array([[6, 3],
       [6, 3]])

In [55]:
def pai_xu(self):
    arr1 = np.random.randint(3,9,10)
    print(arr1)
result = sorted([1,6,9,7,5])
print(result)

[1, 5, 6, 7, 9]


In [60]:
# 内置函数-高阶函数-map()函数
# 功能：对可迭代对象中的每个元素放入自定义函数中，进行实现某种功能
# 参数：可迭代对象，自定义函数
# 返回值：可迭代对象
# practice：
var_list = ["1","5","9","3"]
res = map(int,var_list)
print(res)
print(list(res))  #使用list进行遍历



[1, 5, 9, 3]


In [62]:
# 内置函数-高阶函数-reduce（）
from functools import reduce

"""
先导入：from functools import reduce

功能：每一次从itertable中拿出两个元素，放入到func函数中进行处理，得出一个计算结果，将结果
      再与拿到的第三个元素放入函数中进行处理得出结果，以此类推与第四个元素，第五个元素，直到
      取出所有的元素，得出结果
参数：func，内置函数或者自定义函数
返回值：处理后的结果
     
"""
def myfunc(x,y):
    """
    将varlist= [5,2,1,1,3] 变成52113的值
    """
    return x*10+y

varlist = [5,2,1,1,3]
res = reduce(myfunc,varlist)
print(res,type(res))

52113 <class 'int'>


In [64]:
# 内置函数-高阶函数-filter（） 过滤器
"""
filter（func，iterable）
功能：过滤数据：
参数：自定义函数，可迭代数据
返回值：保留所有的数据，迭代器
"""
def myfunc(n):
    """
    将可迭代对象intlist，进行过滤掉奇数，形成新的迭代对象。。。。
    """
    if n%2==0:
        return True
    else:
        return False
    
intlist= [9,6,7,8,5,5,-1,4,2,0]
res = filter(myfunc,intlist)
print(type(res),list(res))


<class 'filter'> [6, 8, 4, 2, 0]
